// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartArchiver.Data;

#nullable disable

namespace SmartArchiver.Data.Migrations
{
    [DbContext(typeof(SmartArchiverDbContext))]
    partial class SmartArchiverDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SmartArchiver.Data.Entities.MeasurementFileResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<long>("ArchiveBytes")
                        .HasColumnType("bigint");

                    b.Property<byte>("Group")
                        .HasColumnType("tinyint");

                    b.Property<long>("OriginalBytes")
                        .HasColumnType("bigint");

                    b.Property<bool>("Restored")
                        .HasColumnType("bit");

                    b.Property<int>("RunId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RunId");

                    b.ToTable("MeasurementFileResults");
                });

            modelBuilder.Entity("SmartArchiver.Data.Entities.MeasurementRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AllRestored")
                        .HasColumnType("bit");

                    b.Property<double>("Alpha")
                        .HasColumnType("float");

                    b.Property<long>("ArchiveBytes")
                        .HasColumnType("bigint");

                    b.Property<double>("Beta")
                        .HasColumnType("float");

                    b.Property<string>("CommitHash")
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)");

                    b.Property<string>("Dataset")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("ElapsedSeconds")
                        .HasColumnType("float");

                    b.Property<long>("OriginalBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("ParametersJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Q")
                        .HasColumnType("float");

                    b.Property<int?>("Seed")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<double>("TRefSeconds")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("MeasurementRuns");
                });

            modelBuilder.Entity("SmartArchiver.Data.Entities.MeasurementFileResult", b =>
                {
                    b.HasOne("SmartArchiver.Data.Entities.MeasurementRun", "Run")
                        .WithMany("Files")
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Run");
                });

            modelBuilder.Entity("SmartArchiver.Data.Entities.MeasurementRun", b =>
                {
                    b.Navigation("Files");
                });
#pragma warning restore 612, 618
        }
    }
}
